### ISSUE TITLE
Password Change Failed

### ISSUE THREAD

**Issue by RebekkaSp** [Ticket-match/ticketmatch_android#14]

**Comment by Alexxx77** [comment]
What did exactly fail?
Browser: Firefox 46.0.1
I have tried it on Android API 21 on Samsung Galaxy S4 and I do receive the reset email and the link is working.
Please describe the issue in more detail.

**Comment by Alexxx77** [comment]
Sorry, misunderstanding. The password change inside of the application failed.
It might be possible that the user needs to relogin/promt to relogin, so that he can change the password. I will work it out.

**Comment by Alexxx77** [comment]
When you logout and login, the password change works.
More information: https://firebase.google.com/docs/auth/android/manage-users#re-authenticate_a_user
Working on it.
