### ISSUE TITLE
It should only be possible to rate one time per profile

### ISSUE THREAD

**Issue by Smux** [Ticket-match/ticketmatch_android#25]

**Comment by RebekkaSp** [comment]
finde ich ehrlich gesagt nicht, denn du kannst ja einmal jemanden bei makeadate finden und die gleiche person bei tickets. und das eine mal, war die person nett, aber das andere mal ist er/sie nicht aufgetaucht oder oder oder...

**Comment by Smux** [comment]
Mehrfach bewerten an sich ist nicht schlimm, aber man kann unbegrenzt 0 Sterne geben wenn jemand negativ aufgefallen war. Das heißt, dass durch ein negatives Erlebnis die durchschnittliche Bewertung nahe 0 bleiben kann.

**Comment by RebekkaSp** [comment]
Sollen wir einfach das so machen, dass man min 0,5 Sterne vergeben muss?

**Comment by Smux** [comment]
ne lassen es einfach so :)
mir ging es nur darum, dass wenn jemand den anderen nicht mag, er ihm sein ganzes rating mit 100 mal 0 (oder auch 0,5) sterne-bewertungen das rating versauen kann
