### ISSUE TITLE
When rating was given and we go back to chat overview, the chat partner name is displayed multiple times

### ISSUE THREAD

**Issue by Smux** [Ticket-match/ticketmatch_android#26]
Scenario:
You go to a chat -> You go to foreign profile of chat partner -> You give a rating -> you go back to chat overview -> Result : chat partner name is displayed twice (every time you give a rating and then go back to the overview, the rated chat partner name is displayed once more)

**Comment by RebekkaSp** [comment]
Marlon wird beim nächsten Hochladen auch die Lösung dieses Issues dabei haben.
