### ISSUE TITLE
Automated Testing Register Button

### ISSUE THREAD

**Issue by LisaHeim** [Ticket-match/ticketmatch_android#27]
Hi,
Among others, I receive the Perform Exception: 

android.support.test.espresso.PerformException: Error performing 'single click - At Coordinates: 599, 1185 and precision: 16, 16' on view 'with id: de.ticket_match.ticketmatch:id/btnRegister'.

and the AppNotIdleException:
Caused by: android.support.test.espresso.AppNotIdleException: Looped for 3542 iterations over 60 SECONDS. The following Idle Conditions failed .

when clicking the button Register. This does not happen if the Email address is already used for another account (an appropriate toast message pops up).

I am facing this error on multiple other views with other buttons as well.
Please run RegisterTest to see the full error stack.

Can anyone help here?

**Comment by RebekkaSp** [comment]
http://stackoverflow.com/questions/29786413/performexception-error-performing-single-click

Schau mal, ob dir das was hilft

**Comment by LisaHeim** [comment]
Hi,

das habe ich auch schon probiert, auch mit scroll und einem thread der wartet.

Irgendwas muss mit der Registrierung nicht klappen, da hier progressDialog.dismiss(); geschmissen wird.

Könnte da mal jemand in die Klasse Register.java genauer rein schauen?

LG,

Lisa.

**Comment by Alexxx77** [comment]
Hey Lisa,
ich denke das funktioniert ehrlich gesagt alles so wie es soll. Ich bin nicht so tief ins Testen eingearbeitet, daher weiß ich auch nicht wie man das Testen kann. Das Problem liegt aber meiner Meinung nach an folgenden:
Im Test hast du ausschließlich die Register Aktivität geöffnet. Diese wird ausgefüllt und versucht sich dann zu registrieren. Das passt soweit.
Die Registrierung scheint ja auch zu funktionieren, da du anschließend die Fehlermeldung bekommst, dass der Benutzer schon registriert ist.
Das Problem liegt darin, dass du ausschließlich die Register Aktivität testest. Nach einer erfolgreichen Authentifizierung mit Firebase bekommt dies der AuthenticationListener in der MainActivity mit und teilt dem TabHost mit auf den entsprechenden Intent zu wechseln.
Zu finden ist das ganze aktuell in der MainActivity unter Zeile 130 ff.

Weil ansonsten scheint ja auch alles zu funktionieren. Bloß das Umschalten auf die nächste Aktivität scheitert und das ist auf die Verkettung zwischen Register, MainActivity und dem TabHost zurückzuführen.

LG,
Alex

**Comment by LisaHeim** [comment]
Hi Alex und Bekki,

vielen Dank fuer eure Hilfe.
Ich konnte ein Workaround finden, wie ihr im letzten Commit sehen koennt:
https://github.com/Ticket-match/ticketmatch_android/commit/db1721a92e49d3067685405d6bbc93a8027f08eb
Danke,
Lisa.
