### ISSUE TITLE
searching dates fail

### ISSUE THREAD

**Issue by JuKoG** [Ticket-match/ticketmatch_android#31]
get no result by searching dates in "mannheim" even though there are existing entrys for "mannheim"
![screenshot_20160625-103549](https://cloud.githubusercontent.com/assets/19819057/16355747/a443e440-3ac1-11e6-84cd-961bb6e77dfd.png)
![screenshot_20160625-103559](https://cloud.githubusercontent.com/assets/19819057/16355749/a447fd50-3ac1-11e6-85d2-6d878079119d.png)
![screenshot_20160625-103519](https://cloud.githubusercontent.com/assets/19819057/16355748/a445fa82-3ac1-11e6-9896-9a0c54e522c4.png)

**Comment by Alexxx77** [comment]
It is not a bug, it is a feature! You do not see your own entries in the search result, but you should see the entries from another account.
Please test it.

**Comment by Smux** [comment]
no bug
